### ISSUE TITLE
check sender's balance

### ISSUE THREAD

**Issue by xwa130** [Guigulive/Team-G#4]
在FAQ里面，我们有这样一个问题
>#### Q6. @王浩：这个函数不能正确的查询到某个地址的余额是什么原因？
>```javascript
>function getbalance(address person) returns (uint) {
>    return person.balance;
>}
>```
>
>- **@齐明-助教：** 如果用this.balance 可以得到contract的balance，那是因为合约本身，person如果是一个contract，并且有一个可以被外部调用的Function也可以。你现在只是想通过地址来查余额，这个只能从EtherScan上来实现。或者说你在自己的contract里另外建一个variable, 来记录发到某个地址的钱数，日后可以直接调用。
>
我的问题是：在课程中， 我们知道`address` 变量有`.balance` `.transfer` 等变量和方法，那对于`address person` 这个变量， 为什么就不能查询余额了呢？更令人不可以理解的是，既然不能调用`person.balance` 但是却可以调用`person.transfer()`

**Comment by 2liang** [comment]
任何`address`类型的变量都可以直接使用`.balance` `.transfer` 变量和方法，`person` 变量一样可以，他其实和`this`没有本质上的区别，你可以自己测试下。

**Comment by xwa130** [comment]
@2liang 
是的，我测试过了，这个没问题。所以这个回答是错误的对吧。如果错误的答案需要向谁报告来更新呢？

**Comment by 2liang** [comment]
@xwa130 找一下顺达助教吧

**Comment by lsdlinshunda** [comment]
[答案已更新](https://github.com/Guigulive/Wiki/blob/master/daily-review/posts/3/2018.3.12.md#q6-%E7%8E%8B%E6%B5%A9%E8%BF%99%E4%B8%AA%E5%87%BD%E6%95%B0%E4%B8%8D%E8%83%BD%E6%AD%A3%E7%A1%AE%E7%9A%84%E6%9F%A5%E8%AF%A2%E5%88%B0%E6%9F%90%E4%B8%AA%E5%9C%B0%E5%9D%80%E7%9A%84%E4%BD%99%E9%A2%9D%E6%98%AF%E4%BB%80%E4%B9%88%E5%8E%9F%E5%9B%A0)，感谢指正错误
